blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
force_multiline_blocks = true
format_code_in_doc_comments = true
tab_spaces = 2
combine_control_expr = false
